import Toilet from "../../../models/Toilet";
import { openAllWeek, closed } from "../../../utils/time";
import Season from "../../../models/Season";

export function fetchToilets(): Toilet[] {
  return [
    {
      latitude: 60.63042,
      longitude: 8.56398,
      price: 0,
      placement: "Ålingen kjøpesenter, kjeller ved Rema 1000",
      address: "Myren 45, 3570 Ål",
      openingHours: {
        weekday: { from: "07:00", to: "21:00" },
        saturday: { from: "09:00", to: "21:00" },
        sunday: closed,
      },
      accessible: true,
      babycare: false,
      pissoir: false,
    },
    {
      latitude: 60.62996,
      longitude: 8.56231,
      price: 0,
      placement: "Ål kulturhus",
      address: "110/266",
      openingHours: {
        weekday: { from: "09:00", to: "20:00" },
        saturday: { from: "09:00", to: "20:00" },
        sunday: { from: "09:00", to: "20:00" },
      },
      accessible: true,
      babycare: false,
      pissoir: false,
    },
    {
      latitude: 60.63029,
      longitude: 8.56109,
      price: 0,
      placement: "Tingstugu, Ål kommune",
      address: "Torget 1, 3570 ÅL",
      openingHours: {
        weekday: { from: "09:00", to: "15:00" },
        saturday: { from: "09:00", to: "15:00" },
        sunday: { from: "09:00", to: "15:00" },
      },
      accessible: true,
      babycare: false,
      pissoir: false,
    },
    {
      latitude: 60.66437,
      longitude: 8.70649,
      price: 0,
      placement: "Torpo stavkirke",
      address: "11/9, Ål kommune",
      openingHours: openAllWeek,
      accessible: true,
      babycare: false,
      pissoir: false,
    },
    {
      latitude: 60.62884,
      longitude: 8.56168,
      price: 0,
      placement: "Cirkle K",
      address: "Sundrejordet 2, 3570 ÅL",
      openingHours: {
        weekday: { from: "07:00", to: "23:00" },
        saturday: { from: "08:00", to: "23:00" },
        sunday: { from: "09:00", to: "23:00" },
      },
      accessible: true,
      babycare: false,
      pissoir: false,
    },
    {
      latitude: 60.62938,
      longitude: 8.56307,
      price: 0,
      placement: "Sundretunet/Kiwi",
      address: "Helsetunvegen 16A, 3570 ÅL",
      openingHours: {
        weekday: { from: "07:00", to: "23:00" },
        saturday: { from: "07:00", to: "23:00" },
        sunday: { from: "09:00", to: "21:00" },
      },
      accessible: true,
      babycare: false,
      pissoir: false,
    },
    {
      latitude: 60.62641,
      longitude: 8.56224,
      price: 0,
      placement: "Ål stasjon",
      address: "Vestlivegen 2, 3570 ÅL",
      openingHours: openAllWeek,
      accessible: true,
      babycare: false,
      pissoir: false,
    },
    {
      latitude: 60.61623,
      longitude: 8.52884,
      price: 0,
      placement: "Badeplassen",
      address: "123/30, Ål kommune",
      openingHours: openAllWeek,
      accessible: false,
      babycare: false,
      pissoir: false,
      season: "Summer" as Season,
    },
    {
      latitude: 60.62441,
      longitude: 8.54162,
      price: 0,
      placement: "Hallingdal Feriepark",
      address: "Myrovegen 15, 3570 ÅL",
      openingHours: openAllWeek,
      accessible: true,
      babycare: false,
      pissoir: false,
    },
  ].map((toilet) => ({ ...toilet, commune: "Ål" }));
}
