import Toilet from "../../../models/Toilet";
import { openAllWeek } from "../../../utils/time";

export function fetchToilets(): Toilet[] {
  return [
    {
      latitude: 61.90393,
      longitude: 6.72409,
      price: 0,
      placement: "Stryn sentrum",
      address: "Perhusvegen 24",
      openingHours: {
        weekday: { from: "08:00", to: "22:00" },
        saturday: { from: "08:00", to: "22:00" },
        sunday: { from: "08:00", to: "22:00" },
      },
      accessible: true,
      babycare: true,
      pissoir: false,
    },
    {
      latitude: 61.86678,
      longitude: 6.88148,
      price: 0,
      placement: "Lodalen - v/Tyva (mobil toalettvogn)",
      address: "Lodalen",
      openingHours: openAllWeek,
      accessible: false,
      babycare: false,
      pissoir: false,
    },
    {
      latitude: 61.84373,
      longitude: 6.9384,
      price: 0,
      placement: "Lodalen - v/Breng (mobil toalettvogn)",
      address: "Lodalen",
      openingHours: openAllWeek,
      accessible: false,
      babycare: false,
      pissoir: false,
    },
    {
      latitude: 61.83541,
      longitude: 6.80565,
      price: 0,
      placement: "Olden - Sundebygget",
      address: "Olden sentrum",
      openingHours: {
        weekday: { from: "07:00", to: "22:00" },
        saturday: { from: "07:00", to: "22:00" },
        sunday: { from: "07:00", to: "22:00" },
      },
      accessible: true,
      babycare: true,
      pissoir: false,
    },
    {
      latitude: 61.83659,
      longitude: 6.80655,
      price: 0,
      placement: "Olden - midlertidig container",
      address: "Olden sentrum",
      openingHours: openAllWeek,
      accessible: false,
      babycare: false,
      pissoir: false,
    },
    {
      latitude: 61.83892,
      longitude: 6.80913,
      price: 0,
      placement: "Olden - ved terminalområde",
      address: "Olden sentrum",
      openingHours: openAllWeek,
      accessible: true,
      babycare: true,
      pissoir: false,
    },
  ].map((toilet) => ({ ...toilet, commune: "Stryn" }));
}
